[tool.commitizen]
name = "cz_conventional_commits"
version = "0.14.0"
tag_format = "$version"
version_files = [
    "pyproject.toml:version",
    "gyver/__init__.py:__version__"
]
annotated_tag = true