site_name: Gyver
nav:
  - Introduction: index.md
  - Model: usage/model.md
  - Utils: usage/utils.md
  - Config: usage/config.md
  - Database:
      - Working With Database: usage/database/index.md
      - Providers: usage/database/providers.md
      - SQLAlchemy Defaults: usage/database/sqlalchemy.md
      - SQLAlchemy Queries Helper: usage/database/query.md
  - URL: usage/url.md
theme:
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - termynal
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
