name: Deploy Documentation

on:
  push:
    branches:
      - release
    paths-ignore:
      - '*'
    paths:
      - 'docs/**'

env:
  POETRY_VERSION: 1.3.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install -U pip poetry==$POETRY_VERSION
        poetry install --only docs

    - name: Deploy documentation
      run: poetry run mkdocs gh-deploy
      env:
        MKDOCS_VERSION: ${{ env.MKDOCS_VERSION }}
