name: Publish Python Package

on:
  push:
    tags:
      - "*"
env:
  POETRY_VERSION: 1.3.1

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -U pip poetry==$POETRY_VERSION

      - name: Try installing the project
        run: |
          poetry install --all-extras --only main

      - name: Build and publish package
        run: |
          poetry build
          poetry publish -u __token__ -p "${{ secrets.PYPI_TOKEN }}"
        env:
          POETRY_VERSION: ${{ env.POETRY_VERSION }}
      - name: upload package artifacts
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
          ./dist/gyver-${{ github.event.release.tag_name }}-py3-nony-any.whl
          ./dist/gyver-${{ github.event.release.tag_name }}.tar.gz