name: Publish Python Package

on:
  push:
    branches:
      - release
env:
  POETRY_VERSION: 1.3.1

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -U pip poetry==$POETRY_VERSION
    
    - name: Try installing the project
      run: |
        poetry install --all-extras --only main

    - name: Build and publish package
      run: |
        poetry build
        poetry publish -u __token__ -p "${{ secrets.PYPI_TOKEN }}"
      env:
        POETRY_VERSION: ${{ env.POETRY_VERSION }}
